### ISSUE TITLE
stability issues

### ISSUE THREAD

**Issue by darkxst** [herzi/mango-lassi#10]
it turns out mango-lassi is crashing out on me every couple of hours. 

Basically the sharing session disconnects and I get this message
*\* (mango-lassi:3695): WARNING **: Received invalid message: Argument 0 is specified to be of type "int32", but is actually of type "uint32"

after this i have to recreate the session from the preferences dialog.

one machine is 11.10 (onieric) with package from repo (although this one segfaults when try to initiate a connection from its preferences, so I can only iniate sharing session from the 2nd machine)
other machine is 10.04 (lucid) built from source from here

**Comment by herzi** [comment]
Can you please provide a proper stack trace… The warning you posted is known to not lead to crashes.

**Comment by darkxst** [comment]
sure will get you a stack trace of the seg fault, however I have no idea how to get a back trace of the session dropping out.
