### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by kartikm** [herzi/mango-lassi#4]
Hi,

Current README doesn't include details on how to use package. Can we have better documentation on usage. Manpage is not enough for users.

Lets start putting content in wiki and then we can make better docs out of it to put into package.

Thanks.

**Comment by herzi** [comment]
I actually think that having a proper man-page is enough for now.

At some point we might want to have some proper gnome-doc-utils based documentation (which can be properly translated), but the README tells enough, I think.

Also, using mango-lassi is pretty simple. Maybe the only thing that's missing is a notification bubble emphasizing the newly created status icon.

**Comment by herzi** [comment]
I added a basic manual for mango lassi to the git repository:
http://github.com/herzi/mango-lassi/commit/1094c8d2f334172f0ee3ea5070ad803ff91b2274
http://github.com/herzi/mango-lassi/commit/aefc407245cef14192c9808f74aa056a778d5aea
http://github.com/herzi/mango-lassi/commit/384a32353b7bda6a161769be204064b4a3772cd8

If there is any more information that you'd like to see here, feel free to open a new bug report.

**Comment by kartikm** [comment]
Looks nice. Thanks!
